version: '3.9'

########################### NETWORKS
# You may customize the network subnet (192.168.89.0/24) below as you 
# please. Docker Compose version 3.5 or higher required to define networks this way.

networks:
  default:
    driver: bridge
  proxynet:
    name: proxynet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24
# If you decide to use Socket Proxy, you need socket_proxy network as we. 
# See https://www.smarthomebeginner.com/traefik-docker-security-best-practices/#9_Use_a_Docker_Socket_Proxy

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections
# More Info on how to use this: https://github.com/htpcBeginner/docker-traefik/pull/228

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-proxy: &common-keys-proxy
  networks:
    - proxynet
  security_opt:
    - no-new-privileges:true
  restart: always

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  networks:
    - proxynet
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

# Keys common to some of the services in media-services.txt
x-common-keys-media: &common-keys-media
  networks:
    - proxynet
  security_opt:
    - no-new-privileges:true
  restart: "no"


########################### SERVICES
services:

############################# FRONTENDS

# Nginx Proxy Manager - Reverse Proxy with LetsEncrypt
  npm:
    <<: *common-keys-proxy # See EXTENSION FIELDS at the top
    container_name: npm
    image: jc21/nginx-proxy-manager:latest
    # For Static IP
    networks:
    # For Static IP
      proxynet:
        ipv4_address: 192.168.89.81 # You can specify a static IP
   # For Dynamic IP
   # networks:
   #   - proxynet
    ports:
      - 80:80 # Public HTTP Port. Port Forwarding on Router is ON.
      - 443:443 # Public HTTPS Port. Port Forwarding on Router is ON.
      - 81:81 # Admin Web Port. Port Forwarding on Router is OFF. Internal Home Network Access only - 192.168.89.81:81.
    # security_opt:
    # - no-new-privileges:true
    volumes:
    # - $DOCKERDIR/appdata/npm/config:/config
    # - $DOCKERDIR/appdata/npm/letsencrypt:/etc/letsencrypt
    # - $DOCKERDIR/appdata/npm/data:/data
      - ./apps/npm:/config
      - ./apps/npm/letsencrypt:/etc/letsencrypt
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
     # PUID: '1000'
     # PGID: '1000'
     # TZ: 'Europe/Stockholm'
      DB_SQLITE_FILE: '/data/database.sqlite'
      DISABLE_IPV6: 'true'
    # restart: unless-stopped
    # restart: always

  # Portainer - WebUI for Containers
  portainer:
    <<: *common-keys-proxy # See EXTENSION FIELDS at the top
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock # Use Docker Socket Proxy and comment this line out, for improved security.
    # command: -H tcp://socket-proxy:2375 # Use this instead, if you have Socket Proxy enabled.
    networks:
      - proxynet
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Use Docker Socket Proxy and comment this line out, for improved security.
      - $DOCKERDIR/appdata/portainer/data:/data # Change to local directory if you want to save/transfer config locally.
    environment:
      TZ: '$TZ'
      # - TZ=$TZ

  # Heimdall - Application Dashboard
  heimdall:
    <<: *common-keys-proxy # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    ports:
      - '83:80' # 80 to 82 already taken by other services
      # - '444:443' # 443 used by Nginx Proxy Manager. Disabled because we will put Heimdall behind proxy.
    volumes:
      - $DOCKERDIR/appdata/heimdall:/config
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top

  ############################# DOWNLOADERS

  # Torrent Downloader
  deluge:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    networks:
      proxynet:
        ipv4_address: 192.168.89.83 # You can specify a static IP
    ports:
      - '8112:8112'
      - '6881:6881'
      - '6881:6881/udp'
    volumes:
      - $DOCKERDIR/appdata/deluge:/config
      - $DOWNLOADDIR/downloads:/data/downloads
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
      # PUID: '1000'
      # PGID: '1000'
      # TZ: 'Europe/Stockholm'
      DELUGE_LOGLEVEL: 'error' #optional

  # Youtube Downloader and many more
  metube:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: alexta69/metube:latest
    container_name: metube
    networks:
      proxynet:
        ipv4_address: 192.168.89.85 # You can specify a static IP
    ports:
      - '8081:8081'
    volumes:
      - $DOCKERDIR/appdata/metube:/config
      - $DOWNLOADDIR/downloads/metube/videos:/data/downloads/videos
      - $DOWNLOADDIR/downloads/metube/mp3:/data/downloads/mp3
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
      # PUID: '1000'
      # PGID: '1000'
      # TZ: 'Europe/Stockholm'
      UMASK: '022'
      DARK_MODE: 'true'
      DOWNLOAD_DIR: '/data/downloads/videos'
      AUDIO_DOWNLOAD_DIR: '/data/downloads/mp3'
     #  YTDL_OPTIONS: #optional

  ############################# Indexer

  # Prowlarr - Indexer Proxy
  prowlarr:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      proxynet:
        ipv4_address: 192.168.89.87 # You can specify a static IP
    ports:
      - '9696:9696'
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
      # PUID: '1000'
      # PGID: '1000'
      # TZ: 'Europe/Stockholm'

  #  Jackett - Indexer Proxy
  jackett:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    networks:
      proxynet:
        ipv4_address: 192.168.89.89 # You can specify a static IP
    ports:
      - '9117:9117'
    volumes:
      - $DOCKERDIR/appdata/jackett:/config
      - $DOWNLOADDIR/downloads:/data/downloads
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
      # PUID: '1000'
      # PGID: '1000'
      # TZ: 'Europe/Stockholm'
      AUTO_UPDATE: 'true' #optional
      # RUN_OPTS: '' #optional

############################# Management Arr-apps

  # Radarr - Movie management
  radarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      proxynet:
        ipv4_address: 192.168.89.91 # You can specify a static IP
    ports:
      - '7878:7878'
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DOWNLOADDIR/downloads:/data/downloads
      - $DATAMOVDIR/movies:/data/movies
      - $DATAMOVDIR/movies-kids:/data/movies-kids
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
      # PUID: '1000'
      # PGID: '1000'
      # TZ: 'Europe/Stockholm'

  # Sonarr - TV Shows management
  sonarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      proxynet:
        ipv4_address: 192.168.89.93 # You can specify a static IP
    ports:
      - '8989:8989'
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $DATATVDIR/tvshow:/data/shows
      - $DATATVDIR/tvshow-kids:/data/shows-kids
      - $DOWNLOADDIR/downloads:/data/downloads
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
      # PUID: '1000'
      # PGID: '1000'
      # TZ: 'Europe/Stockholm'

  # Lidarr - Music Management
  lidarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      proxynet:
        ipv4_address: 192.168.89.95 # You can specify a static IP
    ports:
      - '8686:8686'
    volumes:
      - $DOCKERDIR/appdata/lidarr:/config
      - $DATADIR/music:/data/music
      - $DOWNLOADDIR/downloads:/data/downloads
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top

  # Readarr - Books management
  readarr:
  <<: *common-keys-media # See EXTENSION FIELDS at the top
  image: hotio/readarr:nightly
  container_name: readarr
  networks:
    proxynet:
      ipv4_address: 192.168.89.97 # You can specify a static IP
  ports:
    - '8987:8987'
  volumes:
    - $DOCKERDIR/appdata/readarr:/config
    - $DATADIR/books:/data/books
    - $DOWNLOADDIR/downloads:/data/downloads
    - '/etc/localtime:/etc/localtime:ro'
  environment:
    <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
    UMASK: '002'
    #ARGS: ""

  # Bazarr - Subtitle  Management
  bazarr:
    <<: *common-keys-media # See EXTENSION FIELDS at the top
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      proxynet:
        ipv4_address: 192.168.89.99 # You can specify a static IP
    ports:
      - '6767:6767'
    volumes:
      - $DOCKERDIR/appdata/bazarr:/config
      - $DATADIR:/data
      - $DOWNLOADDIR/downloads:/data/downloads
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      <<: *default-tz-puid-pgid # See EXTENSION FIELDS at the top
      # PUID: '1000'
      # PGID: '1000'
      # TZ: 'Europe/Stockholm'

############################# MEDIA

  # Jellyfin - Media Server
  jellyfin:
    <<: *common-keys-apps
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      PUID: '1000'
      PGID: '1000'
      TZ: 'Europe/Stockholm'
      UMASK: '022'
    # JELLYFIN_PublishedServerUrl: '192.168.0.5' #optional
    volumes:
      - ./apps/jellyfin:/config
      - /storage/movflix:/storage/movies
      - /storage/shownet/tvshow:/storage/tv
    ports:
      - '8096:8096'
      - '8920:8920' #optional
      - '7359:7359/udp' #optional
      - '1900:1900/udp' #optional
   # restart: unless-stopped

  wiki_db:
    image: postgres:14.1-alpine
    restart: always
    networks:
      - proxynet
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    environment:
      POSTGRES_USER: 'tjelite_admin'
      POSTGRES_PASSWORD: 'Tj5579!!'
      POSTGRES_DB: 'wiki_db'
    ports:
      - '5432:5432'
    volumes:
      - wiki_db:/var/lib/postgresql/data

  wikijs:
    <<: *common-keys-apps
    container_name: wiki
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - wiki_db
    environment:
      DB_TYPE: 'postgres'
      DB_HOST: 'wiki_db'
      DB_PORT: '5432'
      DB_USER: 'tjelite_admin'
      DB_PASS: 'Tj5579!!'
      DB_NAME: 'wiki_db'
      #CONFIG_FILE: '$CONFIG_FILE'
   # restart: unless-stopped
    ports:
      - '3000:3000'

volumes:
  wiki_db:
    driver: local
